WebProject/Controllers/ActorsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using WebProject.Data.Roles;
using WebProject.Data.Services;
using WebProject.Models;

namespace WebProject.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]

    public class ActorsController : Controller
    {
        private readonly IActorsService _service;
        public ActorsController(IActorsService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var data = await _service.GetAllAsync();
            return View(data);
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create([Bind("FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.AddAsync(actor);
            return RedirectToAction(nameof(Index));
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("Empty");
            return View(actorDetails);
        }


        public async Task<IActionResult> Edit(int id )
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("Empty");
            return View(actorDetails);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,FullName,ProfilePictureURL,Bio")] Actor actor)
        {
            if (!ModelState.IsValid)
            {
                return View(actor);
            }
            await _service.UpdateAsync(id,actor);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Delete(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("Empty");
            return View(actorDetails);
        }

        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var actorDetails = await _service.GetByIdAsync(id);
            if (actorDetails == null) return View("Empty");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }


    }
}

WebProject/Controllers/CinemasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebProject.Data;
using WebProject.Data.Roles;
using WebProject.Data.Services;
using WebProject.Models;

namespace WebProject.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class CinemasController : Controller
    {
        private readonly ICinemasService _service;
        public CinemasController(ICinemasService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allProducers = await _service.GetAllAsync();
            return View(allProducers);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("Empty");
            return View(cinemaDetails);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("Logo,Name,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid) return View(cinema);
            await _service.AddAsync(cinema);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Edit(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("Empty");
            return View(cinemaDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Logo,Name,Description")] Cinema cinema)
        {
            if (!ModelState.IsValid) return View(cinema);
            if (id == cinema.Id)
            {
                await _service.UpdateAsync(id, cinema);
                return RedirectToAction(nameof(Index));
            }
            return View(cinema);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("Empty");
            return View(cinemaDetails);
        }
        [HttpPost, ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var cinemaDetails = await _service.GetByIdAsync(id);
            if (cinemaDetails == null) return View("Empty");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

WebProject/Controllers/MoviesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Query.Internal;
using System;
using WebProject.Data;
using WebProject.Data.Roles;
using WebProject.Data.Services;
using WebProject.Data.ViewModel;
using WebProject.Models;

namespace WebProject.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class MoviesController : Controller
    {
        private readonly IMoviesService _service;
        public MoviesController(IMoviesService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index(int ItemSelected, int page = 1)
        {
            var allMovies = await _service.GetAllAsync(n => n.Cinema);
            IEnumerable<Movie> filterResult = allMovies;
            if (ItemSelected == 0) filterResult = allMovies;
            else if (ItemSelected == 1)
            {
                filterResult = allMovies.Where(n => DateTime.Now >= n.StartDate && DateTime.Now <= n.EndDate).ToList();
            }
            else if (ItemSelected == 2)
            {
                filterResult = allMovies.Where(n => DateTime.Now > n.EndDate).ToList();
            }
            else if (ItemSelected == 3)
            {
                filterResult = allMovies.Where(n => DateTime.Now < n.StartDate).ToList();
            }
            int totalItems = filterResult.Count();
            int pageSize = 3;
            int totalPages = (int)Math.Ceiling((double)totalItems / pageSize);

            var paginatedData = filterResult.Skip((page - 1) * pageSize).Take(pageSize);

            ViewBag.CurrentPage = page;
            ViewBag.TotalPages = totalPages;
            ViewBag.ItemSelected = ItemSelected;

            if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
            {
                return PartialView("_PartialIndex", paginatedData);
            }

            return View(paginatedData);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details(int id)
        {
            var movieDetail = await _service.GetMovieByIdAsync(id);
            return View(movieDetail);
        }

        public async Task<IActionResult> Create()
        {
            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(NewMovieVM movie)
        {
            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(movie);
            }

            await _service.AddNewMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }

        public async Task<IActionResult> Edit(int id)
        {
            var movieDetails = await _service.GetMovieByIdAsync(id);
            if (movieDetails == null) return View("Empty");

            var response = new NewMovieVM()
            {
                Id = movieDetails.Id,
                Name = movieDetails.Name,
                Description = movieDetails.Description,
                Price = movieDetails.Price,
                StartDate = movieDetails.StartDate,
                EndDate = movieDetails.EndDate,
                ImageURL = movieDetails.ImageURL,
                MovieCategory = movieDetails.MovieCategory,
                CinemaId = movieDetails.CinemaId,
                ProducerId = movieDetails.ProducerId,
                ActorIds = movieDetails.Actors_Movies.Select(n => n.ActorId).ToList(),
            };

            var movieDropdownsData = await _service.GetNewMovieDropdownsValues();
            ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
            ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
            ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

            return View(response);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int id, NewMovieVM movie)
        {
            if (id != movie.Id) return View("Empty");

            if (!ModelState.IsValid)
            {
                var movieDropdownsData = await _service.GetNewMovieDropdownsValues();

                ViewBag.Cinemas = new SelectList(movieDropdownsData.Cinemas, "Id", "Name");
                ViewBag.Producers = new SelectList(movieDropdownsData.Producers, "Id", "FullName");
                ViewBag.Actors = new SelectList(movieDropdownsData.Actors, "Id", "FullName");

                return View(movie);
            }

            await _service.UpdateMovieAsync(movie);
            return RedirectToAction(nameof(Index));
        }
        // search
        [AllowAnonymous]
        public async Task<IActionResult> Filter(string SearchString)
        {
            var allMovies = await _service.GetAllAsync(n => n.Cinema);

            if (!string.IsNullOrEmpty(SearchString))
            {
                //var filteredResult = allMovies.Where(n => n.Name.ToLower().Contains(searchString.ToLower()) || n.Description.ToLower().Contains(searchString.ToLower())).ToList();

                var filteredResultNew = allMovies.Where(n => string.Equals(n.Name, SearchString, StringComparison.CurrentCultureIgnoreCase) || string.Equals(n.Description, SearchString, StringComparison.CurrentCultureIgnoreCase)).ToList();
                if (filteredResultNew.Count() == 0)
                {
                    return View("Index", allMovies);
                }
                return View("_PartialIndex", filteredResultNew);
            }
            return View("Index", allMovies);
        }
    }
}

WebProject/Controllers/OrdersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using WebProject.Data.Cart;
using WebProject.Data.Roles;
using WebProject.Data.Services;
using WebProject.Data.ViewModel;

namespace WebProject.Controllers
{
    [Authorize]
    public class OrdersController : Controller
    {
        private readonly IMoviesService _moviesService;
        private readonly ShoppingCart _shoppingCart;
        private readonly IOrdersService _ordersService;
        public OrdersController(IMoviesService moviesService, ShoppingCart shoppingCart, IOrdersService ordersService)
        {
            _moviesService = moviesService;
            _shoppingCart = shoppingCart;
            _ordersService = ordersService;

        }
        public IActionResult ShoppingCart()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            _shoppingCart.ShoppingCartItems = items;
            var response = new ShoppingCartVM()
            {
                ShoppingCart = _shoppingCart,
                ShoppingCartTotal = _shoppingCart.GetShoppingCartTotal()
            };
            return View(response);
        }

        public async Task<IActionResult> AddItemToShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.AddItemToCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));   

        }
        public async Task<IActionResult> RemoveItemFromShoppingCart(int id)
        {
            var item = await _moviesService.GetMovieByIdAsync(id);
            if (item != null)
            {
                _shoppingCart.RemoveItemFromCart(item);
            }
            return RedirectToAction(nameof(ShoppingCart));

        }

        public async Task<IActionResult> CompleteOrder()
        {
            var items = _shoppingCart.GetShoppingCartItems();
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userEmailAddress = User.FindFirstValue(ClaimTypes.Email);

            await _ordersService.StoreOrderAsync(items, userId, userEmailAddress);
            await _shoppingCart.ClearShoppingCartAsync();

            return View("OrderCompleted");
        }

        public async Task<IActionResult> Index()
        {
            string userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            string userRole = User.FindFirstValue(ClaimTypes.Role);

            var orders = await _ordersService.GetOrdersByUserIdAndRoleAsync(userId, userRole);
            return View(orders);
        }
    }
}

WebProject/Controllers/ProducersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebProject.Data;
using WebProject.Data.Roles;
using WebProject.Data.Services;
using WebProject.Models;

namespace WebProject.Controllers
{
    [Authorize(Roles = UserRoles.Admin)]
    public class ProducersController : Controller
    {
        private readonly IProducersService _service;
        public ProducersController(IProducersService service)
        {
            _service = service;
        }
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var allProducers = await _service.GetAllAsync();
            return View(allProducers);
        }
        [AllowAnonymous]
        public async Task<IActionResult> Details (int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("Empty");
            return View(producerDetails);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create([Bind("ProfilePictureURL,FullName,Bio")]Producer producer)
        {
            if(!ModelState.IsValid) return View(producer);
            await _service.AddAsync(producer);
            return RedirectToAction(nameof(Index));
        }


        public async Task<IActionResult> Edit(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if(producerDetails == null) return View("Empty");
            return View(producerDetails);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(int id,[Bind("Id,ProfilePictureURL,FullName,Bio")] Producer producer)
        {
            if (!ModelState.IsValid) return View(producer);
            if( id == producer.Id )
            {
                await _service.UpdateAsync(id, producer);
                return RedirectToAction(nameof(Index));
            }
            return View(producer);
        }

        public async Task<IActionResult> Delete(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("Empty");
            return View(producerDetails);
        }
        [HttpPost,ActionName("Delete")]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var producerDetails = await _service.GetByIdAsync(id);
            if (producerDetails == null) return View("Empty");
            await _service.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

    }
}

WebProject/Views/Movies/Details.cshtml
@{
    ViewData["Title"] = "List of Movies";
}

<div class="row">
    <div class="col-md-8 offset-2 align-content-center">
        <div class="card mb-12">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @Model.Name
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-4">
                    <img src="@Model.ImageURL" width="100%" alt="@Model.Name">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <p class="card-text">@Model.Description</p>
                        <p class="card-text">
                            <b>Cinema: </b>
                            <a asp-controller="Cinemas" asp-action="Details" asp-route-id="@Model.CinemaId">
                                @Model.Cinema.Name
                            </a>
                        </p>
                        <p class="card-text">
                            <b>Producer: </b>
                            <a asp-controller="Producers" asp-action="Details" asp-route-id="@Model.ProducerId">
                                @Model.Producer.FullName
                            </a>
                        </p>
                        <p class="card-text"><b>Category: </b>@Model.MovieCategory</p>
                        <p class="card-text"><b>Start Date: </b>@Model.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@Model.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= Model.StartDate && DateTime.Now <= Model.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > Model.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>

                        <div class="card-text w-100">
                            <b>Actors: </b>
                            @* <hr /> *@
                            <div class="row flex-nowrap w-100">
                                @foreach (var actor in Model.Actors_Movies)
                                {
                                    <div class="column text-center w-auto">
                                        <img class="border-info rounded-circle" src="@actor.Actor.ProfilePictureURL" style="max-width: 75px" />
                                        <br />
                                        <a asp-controller="Actors" asp-action="Details" asp-route-id="@actor.Actor.Id">@actor.Actor.FullName</a>
                                    </div>
                                }
                            </div>
                        </div>

                    </div>
                </div>
                <div class="col-md-12">
                    <div class="card-footer">
                        <p class="card-text">
                            <a class="btn btn-outline-primary float-right" asp-action="Index">
                                Back
                            </a>
                            <a class="btn btn-success text-white" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@Model.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart (Price @Model.Price.ToString("c"))
                            </a>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebProject/Views/Movies/Index.cshtml
@model IEnumerable<Movie>

@{
    ViewData["Title"] = "List of Movies";
}
@*write Code*@
<form class="mt-3" asp-controller="Movies" asp-action="Index">
    <select class="form-select form-select-sm mb-3 col-lg-2" name="ItemSelected" id="filterDropdown" aria-label="Large select example">
        <option selected disabled>Status</option>
        <option value=0>ALL</option>
        <option value=1>AVAILABLE</option>
        <option value=2>EXPIRED</option>
        <option value=3>UPCOMING</option>
    </select>
</form>

<div class="row" id="pagination"></div>

<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function () {
        // Xử lý sự kiện onchange của dropdown list
        $('#filterDropdown').change(function () {
            var selectedValue = $(this).val();
            loadPage(1, selectedValue); // Trang đầu tiên là 1
        });

        // Xử lý sự kiện click của các liên kết phân trang
        $(document).on('click', '.pagination-link', function () {
            var page = $(this).data('page');
            var selectedValue = $('#filterDropdown').val();
            loadPage(page, selectedValue);
        });

        // Hàm gửi yêu cầu Ajax để lấy dữ liệu lọc và phân trang
        function loadPage(page, selectedValue) {
            $.ajax({
                url: '@Url.Action("Index", "Movies")',
                type: 'GET',
                data: { page: page, ItemSelected: selectedValue },
                success: function (result) {
                    // Cập nhật danh sách phim và điều khiển phân trang
                    $('#pagination').html(result);
                },
                error: function (xhr, status, error) {
                    // Xử lý lỗi
                    console.log(error);
                }
            });
        }

        // Tải trang đầu tiên khi trang được tải lần đầu
        loadPage(1, $('#filterDropdown').val());
    });
</script>

@await Html.PartialAsync("_CreateItem", "Movies")  

WebProject/Views/Movies/_PartialIndex.cshtml
@model IEnumerable<Movie>
@foreach (var item in Model)
{
    <div class="col-md-4 border-primary mb-3">
        <div class="card mb-3 h-100 position-relative">
            <div class="row g-0">
                <div class="col-md-12">
                    <div class="card-header text-white bg-info">
                        <p class="card-text">
                            <h5 class="card-title">
                                @item.Name
                                @if (User.Identity.IsAuthenticated && User.IsInRole("Admin"))
                                {
                                    <a class="text-white float-right" asp-action="Edit" asp-route-id="@item.Id"><i class="bi bi-pencil-square"></i></a>
                                }
                            </h5>
                        </p>
                    </div>
                </div>
                <div class="col-md-6">
                    <img src="@item.ImageURL" width="100%" alt="@item.Name">
                </div>
                <div class="col-md-6">
                    <div class="card-body">
                        <p class="card-text">@item.Description</p>
                        <p class="card-text"><b>Cinema: </b>@item.Cinema.Name</p>
                        <p class="card-text"><b>Category: </b>@item.MovieCategory</p>
                        <p class="card-text"><b>Start Date: </b>@item.StartDate.ToString("dd MMM yy")</p>
                        <p class="card-text"><b>End Date: </b>@item.EndDate.ToString("dd MMM yy")</p>
                        <p class="card-text ">
                            <b>Status: </b>
                            @if (DateTime.Now >= item.StartDate && DateTime.Now <= item.EndDate)
                            {
                                <span class="badge bg-success text-white">AVAILABLE</span>
                            }
                            else if (DateTime.Now > item.EndDate)
                            {
                                <span class="badge bg-danger text-white">EXPIRED</span>
                            }
                            else
                            {
                                <span class="badge bg-primary text-white">UPCOMING</span>
                            }
                        </p>

                    </div>
                </div>
                <div style="height: 150px;"></div>
                <div class="col-md-12 position-absolute bottom-0 start-50 translate-middle-x">
                    <div class="card-footer d-flex flex-wrap justify-content-center col-md-12">
                        <div class="card-text col-md-12">
                            <a class="btn btn-outline-primary w-100 m-2" asp-action="Details" asp-route-id="@item.Id">
                                Show Details
                            </a>
                        </div>
                        <div class="card-text col-md-12">
                            <a class="btn btn-success text-white w-100 m-2" asp-controller="Orders" asp-action="AddItemToShoppingCart" asp-route-id="@item.Id">
                                <i class="bi bi-cart-plus"></i> Add to Cart <br> (Price @item.Price.ToString("c"))
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


<nav class="pagination justify-content-center">
    <ul class="pagination justify-content-center">
        @if (ViewBag.CurrentPage > 1)
        {
            int i = ViewBag.CurrentPage - 1;
            <li class="page-item pagination-link" data-page="@i"><a class="page-link">Previous</a> </li>
        }
        @if (ViewBag.TotalPages > 1)
        {
            for (int i = 1; i <= ViewBag.TotalPages; i++)
            {
                <li class="page-item pagination-link" data-page="@i"><a class="page-link">@i</a> </li>
            }
        }
        @if (ViewBag.CurrentPage < ViewBag.TotalPages)
        {
            int i = ViewBag.CurrentPage + 1;
            <li class="page-item pagination-link" data-page="@i"><a class="page-link">Next</a> </li>
        }
    </ul>
</nav>